apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-three-tier-1
  region: ap-south-1
  version: "1.29"

nodeGroups:
  - name: ng-three-tier
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
